openapi: 3.0.0
info:
  title: Dog Breeds API
  version: 1.0.0
paths:
  /api/dogs:
    get:
      summary: Get a list of dog breeds
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: A list of dog breeds
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    breed:
                      type: string
                    image:
                      type: string
                      nullable: true
        400:
          description: Bad Request
        500:
          description: Internal Server Error
